function bestSegment(road,p){let best=null;for(let i=0;i<road.points.length-1;i++){const a=road.points[i],b=road.points[i+1],d=lineDistance(p,a,b),br=bearing(a.lat,a.lon,b.lat,b.lon);if(!best||d<best.distance)best={road,a,b,index:i,distance:d,bearing:br}}return best}
function matchRoads(roads,p){const candidates=[];for(const road of roads){const s=bestSegment(road,p);if(!s)continue;let score=s.distance;const moving=(p.speed??0)>2.2;let dir=0;if(p.heading!=null){const f=angleDiff(p.heading,s.bearing),b=angleDiff(p.heading,(s.bearing+180)%360);dir=Math.min(f,b);score+=dir*(moving?.35:.08);const ow=String(road.oneWay||road.tags?.oneway||'').toUpperCase();let wrong=false;if(['YES','1','TRUE','FT'].includes(ow))wrong=f>95;if(['-1','TF'].includes(ow))wrong=b>95;if(wrong&&moving)score+=100}if(state.lastMatch){const same=road.id===state.lastMatch.road.id,sameName=normName(road.name)&&normName(road.name)===normName(state.lastMatch.road.name);if(same){if(!moving||p.heading==null||dir<50)score-=20;else if(dir>70)score+=18}else if(sameName&&(!moving||p.heading==null||dir<50))score-=7}if(road.source==='spartanburg')score-=3;if(road.source==='scdot')score-=2;candidates.push({...s,score,dir})}candidates.sort((a,b)=>a.score-b.score);const max=Math.max(24,Math.min(CFG.matchMaxM,(p.accuracy||20)*1.5));return{best:candidates[0]&&candidates[0].distance<=max?candidates[0]:null,candidates:candidates.slice(0,24)}}
function localCorrections(){try{return JSON.parse(localStorage.getItem('roadlimitCorrectionsV3')||'[]')}catch{return[]}}
function getCorrection(match,p){if(!match)return null;const key=match.road.id,name=normName(match.road.name);return localCorrections().filter(c=>{const d=meters(c.lat,c.lon,p.lat,p.lon);return(c.roadId===key&&d<800)||(name&&c.roadName===name&&d<120)}).sort((a,b)=>meters(a.lat,a.lon,p.lat,p.lon)-meters(b.lat,b.lon,p.lat,p.lon))[0]||null}
function speedFromRoad(road,p,seg){if(road.source==='osm')return osmDirectionalSpeed(road.tags||{},p.heading,seg?.bearing);return road.speed}
function resolveLimit(matchPack,p){const {best,candidates}=matchPack;if(!best)return{display:CFG.unknownDisplay,mph:null,source:'Estimated',confidence:'low',road:'Unknown road',roadId:null};const correction=getCorrection(best,p);if(correction)return{display:correction.mph,mph:correction.mph,source:'Verified correction',confidence:'high',road:best.road.name||'Current road',roadId:best.road.id};const chosen=best.road;const nearby=candidates.filter(c=>{const close=c.distance<=Math.max(24,(p.accuracy||15)*1.25);if(!close)return false;if(c.road.id===chosen.id)return true;const sameName=chosen.name&&c.road.name&&normName(c.road.name)===normName(chosen.name);const parallel=Math.min(angleDiff(c.bearing,best.bearing),angleDiff(c.bearing,(best.bearing+180)%360))<=25;const colocated=c.distance<=14&&parallel;return sameName||colocated});let options=[];for(const c of nearby){const v=speedFromRoad(c.road,p,c);if(v==null)continue;let pri=CFG.sourcePriority[c.road.source]||0;if(c.road.source==='scdot'&&String(chosen.owner||'').toUpperCase().includes('SCDOT'))pri+=8;options.push({mph:v,pri,road:c.road,seg:c})}if(state.hardware&&Date.now()-state.hardware.ts<15000&&state.hardware.mph!=null)options.push({mph:state.hardware.mph,pri:CFG.sourcePriority.esp32+(state.hardware.confidence||0)*10,road:{source:'esp32',name:chosen.name}});options.sort((a,b)=>b.pri-a.pri);if(!options.length)return{display:CFG.unknownDisplay,mph:null,source:'Estimated',confidence:'low',road:chosen.name||'Current road',roadId:chosen.id};const top=options[0],conflict=options.some(o=>o!==top&&o.pri>=75&&Math.abs(o.mph-top.mph)>=5),conditional=top.road.source==='osm'&&Boolean(top.road.tags?.['maxspeed:conditional']);const labels={spartanburg:'Spartanburg County',scdot:'SCDOT',osm:'OpenStreetMap',esp32:'ESP32'};return{display:top.mph,mph:top.mph,source:labels[top.road.source]||top.road.source,confidence:(conflict||conditional)?'medium':'high',conflict,conditional,road:chosen.name||top.road.name||'Current road',roadId:chosen.id}}
function smoothFix(raw){if(!state.lastSmooth)return raw;const d=meters(state.lastSmooth.lat,state.lastSmooth.lon,raw.lat,raw.lon);if(d>250&&((raw.speed??0)<40))return state.lastSmooth;const acc=Math.max(3,raw.accuracy||20),alpha=Math.max(.35,Math.min(.82,18/acc));return{...raw,lat:state.lastSmooth.lat+(raw.lat-state.lastSmooth.lat)*alpha,lon:state.lastSmooth.lon+(raw.lon-state.lastSmooth.lon)*alpha}}
function deriveHeading(p){if(p.heading!=null&&Number.isFinite(p.heading)&&p.speed!=null&&p.speed>1.2)return p.heading;if(state.lastSmooth&&meters(state.lastSmooth.lat,state.lastSmooth.lon,p.lat,p.lon)>5)return bearing(state.lastSmooth.lat,state.lastSmooth.lon,p.lat,p.lon);return p.heading}
function primeSpeech(){try{const u=new SpeechSynthesisUtterance('.');u.volume=0;speechSynthesis.speak(u)}catch{}}
function announce(res){const now=Date.now();if(now-state.lastAnnounce<CFG.announceCooldownMs)return;const text=res.mph==null?'Speed limit, approximately 35 miles per hour':`Speed limit, ${res.mph} miles per hour`;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.volume=1;speechSynthesis.speak(u);state.lastAnnounce=now}catch{}}
function commitLimit(res,p){const key=res.mph==null?'unknown':String(res.mph);if(state.pendingLimit!==key){state.pendingLimit=key;state.pendingCount=1;return false}state.pendingCount++;if(state.pendingCount<CFG.limitStableFixes)return false;const lastKey=state.lastLimit?.mph==null?(state.lastLimit?'unknown':null):String(state.lastLimit.mph);if(lastKey!==key){state.lastLimit=res;state.events.push({t:Date.now(),lat:p.lat,lon:p.lon,mph:res.mph,display:res.display,source:res.source,confidence:res.confidence,road:res.road,roadId:res.roadId});announce(res);return true}state.lastLimit={...state.lastLimit,...res};return false}
function renderDrive(res,p){$('limit').textContent=res.display;$('roadName').textContent=res.road;$('sourcePill').textContent=`${res.source.toUpperCase()} • ${res.confidence.toUpperCase()}${res.conflict?' • CONFLICT':''}`;$('confidence').textContent=res.conflict?'Two map sources disagree — showing the higher-priority source':res.conditional?'Conditional speed rule mapped — showing the base limit':`${res.source} • GPS ±${Math.round(p.accuracy||0)} m`;$('gpsStatus').textContent=`GPS ±${Math.round(p.accuracy||0)} m`;$('trackStatus').textContent=`${state.track.length} points`}
async function onPosition(pos){
 const seq=++state.fixSeq,c=pos.coords,raw={lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,heading:Number.isFinite(c.heading)?c.heading:null,speed:Number.isFinite(c.speed)?c.speed:null,t:pos.timestamp||Date.now()};
 let rec=-1;if(state.recording){rec=state.track.length;state.track.push({...raw,accepted:raw.accuracy<=CFG.gpsRejectM,display:state.lastLimit?.display??'—'})}
 if(raw.accuracy>CFG.gpsRejectM){$('gpsStatus').textContent=`Weak GPS ±${Math.round(raw.accuracy)} m`;$('confidence').textContent='Holding the last matched road until GPS improves';return}
 const p=smoothFix(raw);p.heading=deriveHeading(p);state.lastRaw=raw;const tile=await loadTile(p.lat,p.lon);if(seq!==state.fixSeq)return;
 const pack=matchRoads(tile.roads,p);state.lastMatch=pack.best||state.lastMatch;const res=resolveLimit(pack,p);commitLimit(res,p);const shown=state.lastLimit||res;renderDrive(shown,p);
 if(rec>=0&&state.track[rec])Object.assign(state.track[rec],{matchLat:p.lat,matchLon:p.lon,accepted:true,display:shown.display,mph:shown.mph,source:shown.source,road:shown.road,roadId:shown.roadId});state.lastSmooth=p
}
