function startDrive(){if(!navigator.geolocation){alert('This browser does not provide GPS.');return}primeSpeech();state.recording=true;state.track=[];state.events=[];state.lastRaw=null;state.lastSmooth=null;state.lastMatch=null;state.lastLimit=null;state.pendingLimit=null;state.pendingCount=0;state.fixSeq=0;showScreen('drive');navigator.wakeLock?.request('screen').then(x=>state.wake=x).catch(()=>{});state.watch=navigator.geolocation.watchPosition(onPosition,e=>{$('gpsStatus').textContent=`GPS error: ${e.message}`},{enableHighAccuracy:true,maximumAge:0,timeout:10000})}
async function finishDrive(){state.recording=false;if(state.watch!=null)navigator.geolocation.clearWatch(state.watch);state.watch=null;try{await state.wake?.release()}catch{}const accepted=state.track.filter(x=>x.accepted);const drive={id:`drive-${Date.now()}`,startedAt:accepted[0]?.t||Date.now(),endedAt:accepted.at(-1)?.t||Date.now(),track:state.track,events:state.events};state.lastDrive=drive;await dbPut('drives',drive);localStorage.setItem('roadlimitLastDriveId',drive.id);showScreen('home');reviewDrive(drive)}
function showScreen(id){for(const s of document.querySelectorAll('.screen'))s.classList.toggle('active',s.id===id)}
function overlay(id,on=true){$(id).classList.toggle('active',on)}
function fmtDuration(ms){const m=Math.max(0,Math.round(ms/60000));return m<60?`${m} min`:`${Math.floor(m/60)}h ${m%60}m`}
function driveDistance(track){let d=0,last=null;for(const p of track.filter(x=>x.accepted)){if(last)d+=meters(last.lat,last.lon,p.lat,p.lon);last=p}return d}
async function reviewDrive(drive){if(!drive)return;overlay('review',true);const pts=drive.track.filter(x=>x.accepted&&Number.isFinite(x.lat)&&Number.isFinite(x.lon));const mi=driveDistance(drive.track)/1609.344,maxMph=Math.max(0,...pts.map(p=>(p.speed||0)*2.236936));$('reviewSummary').innerHTML=`<div class="stat"><b>${mi.toFixed(1)}</b><span>miles</span></div><div class="stat"><b>${fmtDuration(drive.endedAt-drive.startedAt)}</b><span>duration</span></div><div class="stat"><b>${Math.round(maxMph)}</b><span>max GPS mph</span></div>`;drawReviewMap(drive,pts);renderEvents(drive);await reviewSigns(drive,pts)}
function drawReviewMap(drive,pts){const el=$('reviewMap');if(!window.L){el.innerHTML='<div class="card">Map library did not load. Your drive is still saved.</div>';return}if(state.reviewMap){state.reviewMap.remove();state.reviewMap=null}if(!pts.length)return;const map=L.map(el);state.reviewMap=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const line=L.polyline(pts.map(p=>[p.lat,p.lon]),{weight:6}).addTo(map);L.marker([pts[0].lat,pts[0].lon]).addTo(map).bindPopup('<b>Start</b>');L.marker([pts.at(-1).lat,pts.at(-1).lon]).addTo(map).bindPopup('<b>Finish</b>');for(const e of drive.events||[])L.circleMarker([e.lat,e.lon],{radius:7,weight:2,fillOpacity:.9}).addTo(map).bindPopup(`<b>${e.display} MPH</b><br>${e.road}<br>${e.source}`);map.fitBounds(line.getBounds(),{padding:[25,25]});setTimeout(()=>map.invalidateSize(),150)}
function renderEvents(drive){const box=$('reviewEvents');box.innerHTML='<div class="card"><b>Detected speed-limit changes</b><div class="event-meta">Confirm known values, or enter the actual posted limit. Estimated ~35 values are never promoted to verified data unless you enter a real sign value.</div></div>';for(const e of drive.events||[]){const c=document.createElement('div');c.className='card event-row';const known=e.mph!=null;c.innerHTML=`<div class="event-limit">${e.display}</div><div><b>${e.road}</b><div class="event-meta">${e.source} • ${e.confidence}</div></div><div class="event-actions">${known?'<button data-ok>Confirm</button>':''}<button data-change>${known?'Change':'Set actual'}</button></div>`;const ok=c.querySelector('[data-ok]');if(ok)ok.onclick=()=>saveCorrection(e,e.mph,c);c.querySelector('[data-change]').onclick=()=>{const v=Number(prompt('What did the posted sign say (MPH)?',e.mph??''));if(validOfficialSpeed(v))saveCorrection(e,v,c)};box.appendChild(c)}}
function saveCorrection(e,mph,card){const a=localCorrections();a.push({roadId:e.roadId,roadName:normName(e.road),lat:e.lat,lon:e.lon,mph,time:new Date().toISOString()});localStorage.setItem('roadlimitCorrectionsV3',JSON.stringify(a.slice(-500)));card.style.opacity='.55';const b=card.querySelector('[data-ok]');if(b)b.textContent='Saved'}
function driveBBox(pts){if(!pts.length)return null;const la=pts.map(x=>x.lat),lo=pts.map(x=>x.lon);return[Math.min(...la)-.0015,Math.min(...lo)-.0015,Math.max(...la)+.0015,Math.max(...lo)+.0015]}
async function querySigns(pts){const b=driveBBox(pts);if(!b)return[];const q=`[out:json][timeout:20];node["traffic_sign"~"maxspeed"](${b.join(',')});out tags;`;let err;for(const ep of URLS.overpass){try{const r=await timeoutFetch(ep,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:q},15000);if(!r.ok)throw Error();const j=await r.json();return(j.elements||[]).map(n=>({id:n.id,lat:n.lat,lon:n.lon,mph:parseMph(n.tags?.maxspeed,'km/h'),tags:n.tags||{}})).filter(s=>Math.min(...pts.map(p=>meters(p.lat,p.lon,s.lat,s.lon)))<120)}catch(e){err=e}}throw err}
async function reviewSigns(drive,pts){const box=$('signReview');box.innerHTML='<div class="card">Checking OpenStreetMap for mapped speed-limit signs near your route…</div>';try{const signs=await querySigns(pts);if(!signs.length){box.innerHTML='<div class="card">No mapped speed-limit sign points were found near this drive.</div>';return}box.innerHTML='<div class="card"><b>Mapped sign verification</b><div class="event-meta">These are map records, not proof the physical sign still exists. Verify what you saw.</div></div>';for(const s of signs){const near=drive.events.reduce((best,e)=>meters(e.lat,e.lon,s.lat,s.lon)<meters(best.lat,best.lon,s.lat,s.lon)?e:best,drive.events[0]||{lat:s.lat,lon:s.lon,road:'Nearby road',roadId:null});const c=document.createElement('div');c.className='card event-row';c.innerHTML=`<div class="event-limit">${s.mph??'?'} </div><div><b>Mapped speed-limit sign</b><div class="event-meta">near ${near.road||'your route'}</div></div><div class="event-actions"><button data-ok>Verified</button><button data-change>Wrong / change</button></div>`;c.querySelector('[data-ok]').onclick=()=>{if(s.mph)saveCorrection({...near,lat:s.lat,lon:s.lon},s.mph,c)};c.querySelector('[data-change]').onclick=()=>{const v=Number(prompt('Actual posted MPH?',''));if(validOfficialSpeed(v))saveCorrection({...near,lat:s.lat,lon:s.lon},v,c)};box.appendChild(c)}}catch(e){box.innerHTML='<div class="card">Sign lookup is temporarily unavailable. Your route review is still saved.</div>'}}
function updateDiagnostics(){$('diagBody').textContent=Object.entries(state.sourceHealth).map(([k,v])=>`${k}: ${v}`).join('\n')||'No data source has been queried yet.'}
async function clearCaches(){memTiles.clear();await dbClear('tiles');state.tile=null;updateDiagnostics();$('diagBody').textContent='Road-data cache cleared. Fresh official/OSM data will be requested on the next GPS fix.'}

