const DB_NAME='roadlimit-v3',DB_VER=1;let dbPromise;
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('drives'))db.createObjectStore('drives',{keyPath:'id'});if(!db.objectStoreNames.contains('tiles'))db.createObjectStore('tiles',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
async function dbPut(store,value){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>res(value);tx.onerror=()=>rej(tx.error)})}
async function dbGet(store,key){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbClear(store){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).clear();tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function lastDrive(){const id=localStorage.getItem('roadlimitLastDriveId');return id?dbGet('drives',id):null}

$('startBtn').onclick=startDrive;$('finishBtn').onclick=finishDrive;$('reviewBtn').onclick=async()=>{const d=await lastDrive();if(!d)return alert('No stored drive yet.');reviewDrive(d)};$('closeReview').onclick=()=>overlay('review',false);$('diagBtn').onclick=()=>{updateDiagnostics();overlay('diagnostics',true)};$('closeDiag').onclick=()=>overlay('diagnostics',false);$('clearCachesBtn').onclick=clearCaches;$('deleteDriveBtn').onclick=async()=>{const id=localStorage.getItem('roadlimitLastDriveId');if(id){const db=await openDB();const tx=db.transaction('drives','readwrite');tx.objectStore('drives').delete(id);await new Promise(r=>tx.oncomplete=r)}localStorage.removeItem('roadlimitLastDriveId');overlay('review',false)};
if(window.RoadLimitESP32)RoadLimitESP32.onMessage(msg=>{if(msg.type==='speed_limit'){const mph=validOfficialSpeed(msg.mph);if(mph)state.hardware={mph,confidence:Math.max(0,Math.min(1,Number(msg.confidence)||.8)),ts:Date.now(),raw:msg}}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
